### ISSUE TITLE
Allow users to set a proxy

### ISSUE THREAD

**Issue by kinow** [karussell/snacktory#43]
IIUC, it is not supported at the moment https://github.com/karussell/snacktory/blob/665d54a4b1bf6f87f8944affa5da9ccf4d2b9f72/src/main/java/de/jetwick/snacktory/HtmlFetcher.java#L398

Any chance to have this as a parameter in the future?

**Comment by karussell** [comment]
If you provide it as pull request ;) ?

**Comment by kinow** [comment]
Deal!

**Comment by kinow** [comment]
Done in https://github.com/karussell/snacktory/pull/44

**Comment by kinow** [comment]
Closing since the PR has been merged :-) Thank you!

**Comment by karussell** [comment]
I have to thank :) !
