### ISSUE TITLE
Please don't cause referrer spam

### ISSUE THREAD

**Issue by Flameeyes** [karussell/snacktory#58]
Your software already appears to properly advertise itself in the User-Agent, please don't cause Referer spam by using a fake referer pointing to this repository.

**Comment by karussell** [comment]
What do you mean? Also the software is not actively maintained and you would need to provide a PR to fix the problem.

**Comment by Flameeyes** [comment]
There is something/someone using your library to fetch my blog and the Referer HTTP header is pointing at this repository. If this is not something you are not maintaining actively, I'll just reject those requests from now on.

**Comment by karussell** [comment]
> There is something/someone using your library to fetch my blog

Normally it should not misbehave

> I'll just reject those requests from now on

Sure, go ahead
